geofix_service/account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from .forms import AuthenticationForm
from . import views


urlpatterns = [
    url(r"^register/$", views.register, name="register"),
    url(r"^activate/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$", views.activate,
        name="activate"),
    url(r"^login/$",
        auth_views.LoginView.as_view(template_name="account/login.html",
                                     authentication_form=AuthenticationForm,
                                     redirect_field_name="account/profile/"),
        name="login"),
    url(r"^dashboard/$", views.dashboard, name="dashboard"),
    url(r"^reports/$", views.reports, name="reports"),
    url(r"^logout/$",
        auth_views.LogoutView.as_view(template_name="account/logout.html"),
        name="logout"),
    url(r"^password-change/$", auth_views.PasswordChangeView.as_view(
        template_name="account/password_change_form.html",
        success_url=reverse_lazy("account:password_change_done")),
        name="password_change"),
    url(r"^password-change/done/$", auth_views.PasswordChangeDoneView.as_view(
        template_name="account/password_change_done.html"),
        name="password_change_done"),
    url(r"^password-reset/$", auth_views.PasswordResetView.as_view(
        template_name="account/password_reset_form.html",
        email_template_name="account/password_reset_email.html",
        success_url=reverse_lazy("account:password_reset_done")),
        name="password_reset"),
    url(r"^password-reset/done/$", auth_views.PasswordResetDoneView.as_view(
        template_name="account/password_reset_done.html"),
        name="password_reset_done"),
    url(r"^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/password_reset_confirm.html",
            success_url=reverse_lazy("account:password_reset_complete")),
        name="password_reset_confirm"),
    url(r"^password-reset/complete/$",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="account/password_reset_complete.html"),
        name="password_reset_complete"),
]

geofix_service/geofix_service/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.home),
    url(r'^admin/', admin.site.urls),
    url(r"^upload/", include("upload.urls", namespace="upload")),
    url(r"^account/", include("account.urls", namespace="account")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

geofix_service/upload/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r"^", views.upload_file, name="upload_file"),
]

geofix_service/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=News+Cycle" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Jura:400,600" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Aldrich" rel="stylesheet">

    {% block extra_head %}{% endblock %}
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <div class="container">
	<nav class="navbar navbar-toggleable-md">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <img class="navbar-brand" src="{% static 'images/logo.png' %}" alt="Geofix logo">
        {% if request.path != "/account/login/" %}
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            {% if user.is_authenticated %}
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'account:dashboard' %}">Dashboard</a>
            </div>
            <div class="navbar-nav ml-auto">
                <a class="nav-item nav-link" href="{% url 'account:logout' %}">Logout</a>
            </div>
            {% else %}
            <div class="navbar-nav ml-auto">
                <a class="nav-item nav-link" href="{% url 'account:login' %}">Login</a>
            </div>
            {% endif %}
        </div>
        {% endif %}
	</nav>
    </div>
    <div class="container" id="content">
        {% block content %}{% endblock %}
    </div>

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    {% block js_scripts %}{% endblock %}
  </body>
</html>